apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cert-manager-csi-driver
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: cert-manager-csi-driver
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: cert-manager-csi-driver
      containers:
        - name: node-driver-registrar
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar
          args:
            - -v=1
            - --csi-address=/plugin/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/cert-manager-csi-driver/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: registration-dir
              mountPath: /registration
        - name: liveness-probe
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          image: registry.k8s.io/sig-storage/livenessprobe
          args:
            - --csi-address=/plugin/csi.sock
            - --probe-timeout=3s
            - --health-port=9809
            - -v=1
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
        - name: cert-manager-csi-driver
          securityContext:
            runAsUser: 0
            privileged: true
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          image: quay.io/jetstack/cert-manager-csi-driver
          args :
            - --log-level=1
            - --driver-name=csi.cert-manager.io
            - --node-id=$(NODE_ID)
            - --endpoint=$(CSI_ENDPOINT)
            - --data-root=csi-data-dir
            - --use-token-request=false
            - --metrics-bind-address=:9402
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
            - name: csi-data-dir
              mountPath: /csi-data-dir
              mountPropagation: Bidirectional
          ports:
            - containerPort: 9809
              name: healthz
            - containerPort: 9402
              name: http-metrics
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/cert-manager-csi-driver
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: csi-data-dir
          hostPath:
            path: /tmp/cert-manager-csi-driver
            type: DirectoryOrCreate
