apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cert-manager
  app.kubernetes.io/component: csi-driver
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - csidriver.yaml
  - daemonset.yaml
  - serviceaccount.yaml
images:
  - name: registry.k8s.io/sig-storage/csi-node-driver-registrar
    newTag: v2.17.0@sha256:f9de845b170155199f2a2a3f9531cf13d78e31235e9db6b6582a8b0db0a50dad
  - name: registry.k8s.io/sig-storage/livenessprobe
    newTag: v2.19.0@sha256:06da0d5b8908072f2e4522692aee8dc119fba7247a9658497e1153992cd777e9
  - name: quay.io/jetstack/cert-manager-csi-driver
    newTag: v0.16.0@sha256:9d13db6dc80eb2be9ef0b7cc28ffe1eb9873c5226ca3d1f7818ea5b5fe3bb307
