apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: webhook
resources:
  - deployment.yaml
  - mutating-webhook.yaml
  - rbac.yaml
  - service.yaml
  - serviceaccount.yaml
  - validating-webhook.yaml
configMapGenerator:
  - name: cert-manager-webhook
images:
  - name: quay.io/jetstack/cert-manager-webhook
    newTag: v1.15.2@sha256:b1fcc42bfba229a6783911b0f6b845c14f568c830efd6d35c2b2b74e91a5d3a4
