apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cert-manager
  app.kubernetes.io/component: webhook
resources:
  - deployment.yaml
  - mutating-webhook.yaml
  - rbac.yaml
  - service.yaml
  - serviceaccount.yaml
  - validating-webhook.yaml
configMapGenerator:
  - name: cert-manager-webhook
images:
  - name: quay.io/jetstack/cert-manager-webhook
    newTag: v1.21.1@sha256:d8b3961b51c8c7320633f8208dc46bf88aa13804d0f7cbe48a096b2c523cee42
