apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cert-manager
  app.kubernetes.io/component: controller
resources:
  - ../../configurations/monitoring
  - servicemonitor.yaml
