apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: controller
resources:
  - deployment.yaml
  - rbac.yaml
  - service.yaml
  - serviceaccount.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cert-manager
      spec:
        template:
          spec:
            containers:
              - name: cert-manager-controller
                env:
                  - name: CERT_MANAGER_ACME_HTTP01_SOLVER_IMAGE
                    # renovate: datasource=docker
                    value: quay.io/jetstack/cert-manager-acmesolver:v1.15.2@sha256:ab5eb7bd40f455f4db4d55272ded51cd07a99806c63ff3f6e0d83b29dd8ac667
images:
  - name: quay.io/jetstack/cert-manager-controller
    newTag: v1.15.2@sha256:5339f3e7e86ad672456bb24de8e76887fdd2db8a0c14330d17cdcc13aa945095
