apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cert-manager
  app.kubernetes.io/component: controller
resources:
  - deployment.yaml
  - rbac.yaml
  - service.yaml
  - serviceaccount.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cert-manager
      spec:
        template:
          spec:
            containers:
              - name: cert-manager-controller
                env:
                  - name: CERT_MANAGER_ACME_HTTP01_SOLVER_IMAGE
                    # renovate: datasource=docker
                    value: quay.io/jetstack/cert-manager-acmesolver:v1.20.2@sha256:cfa55e9c3dcfc6a3cba97575748c1549b04a30fd14d88a2fcb9e2dddef415e2f
images:
  - name: quay.io/jetstack/cert-manager-controller
    newTag: v1.20.2@sha256:fe0623d7d04a382c888f03343a3a2da716e0d96ad3d5d790c0ebcbcb2a4329a5
