apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: cert-manager
  app.kubernetes.io/component: controller
resources:
  - deployment.yaml
  - rbac.yaml
  - service.yaml
  - serviceaccount.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cert-manager
      spec:
        template:
          spec:
            containers:
              - name: cert-manager-controller
                env:
                  - name: CERT_MANAGER_ACME_HTTP01_SOLVER_IMAGE
                    # renovate: datasource=docker
                    value: quay.io/jetstack/cert-manager-acmesolver:v1.20.0@sha256:5b8f5c747bf4b966eaa244260ac7c6b513871bc3b7c6e2c4a06c3b143d7c8a75
images:
  - name: quay.io/jetstack/cert-manager-controller
    newTag: v1.20.0@sha256:b9009aa6b45b59da1363a26dab15aee7d77c7ce01ac2c1cf05ecd1121462db16
